### ISSUE TITLE
xml.rb not found

### ISSUE THREAD

**Issue by damiencuvillier** [cjheath/polyglot#10]
On [redmine mylyn-connector plugin](https://github.com/joaopedrotaveira/redmine_mylyn_connector), I'm stucked on running polyglot. 

In polyglot, it said that xml.rb is missing 

``` /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require': No such file to load -- xml.rb (LoadError)```

[Redmine Issue](https://github.com/danmunn/redmine_mylyn_connector/issues/56)

I've tried this. No result
```
apt install libxml2-dev libxslt-dev ruby-dev gcc
gem install libxml-ruby
gem install libxml2-ruby 
gem install bundler

```

Here is my full stack strace. 
```
/usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require': No such file to load -- xml.rb (LoadError)
	from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
	from /usr/src/redmine/plugins/redmine_mylyn_connector/lib/mylyn_connector/controller_test.rb:2:in `<top (required)>'
	from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:378:in `block in require_or_load'
	from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:13:in `loading'
	from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:37:in `load_interlock'
	from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:356:in `require_or_load'
	from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:334:in `depend_on'
	from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:246:in `require_dependency'
	from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
	from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:477:in `each'
	from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:477:in `block in eager_load!'
	from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:475:in `each'
	from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:475:in `eager_load!'
	from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:356:in `eager_load!'
	from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/application/finisher.rb:69:in `each'
	from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
	from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
	from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
	from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
	from /usr/src/redmine/config/environment.rb:16:in `<top (required)>'
	from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
	from config.ru:3:in `block in <main>'
	from /usr/local/bundle/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
	from /usr/local/bundle/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
	from /usr/local/bundle/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
	from /usr/local/bundle/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
	from /usr/local/bundle/gems/rack-2.2.2/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	from /usr/local/bundle/gems/rack-2.2.2/lib/rack/server.rb:249:in `app'
	from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:27:in `app'
	from /usr/local/bundle/gems/rack-2.2.2/lib/rack/server.rb:422:in `wrapped_app'
	from /usr/local/bundle/gems/rack-2.2.2/lib/rack/server.rb:312:in `block in start'
	from /usr/local/bundle/gems/rack-2.2.2/lib/rack/server.rb:379:in `handle_profiling'
	from /usr/local/bundle/gems/rack-2.2.2/lib/rack/server.rb:311:in `start'
	from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:53:in `start'
	from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:142:in `tap'
	from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:142:in `perform'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/command/base.rb:69:in `perform'
	from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/command.rb:46:in `invoke'
	from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

```

**Comment by cjheath** [comment]
This is not an issue with polyglot. Polyglot just hooks require to insert additional options, then calls kernel require, so if you fail to load something using polyglot, you would have also failed without it. I cannot help you know why this happens.
